FROM python:3.10-slim

WORKDIR /usr/mlflow

COPY docker/requirements-dev.txt .
RUN pip install --no-cache-dir -r requirements-dev.txt

COPY docker/requirements-fastapi.txt .
RUN pip install fastapi==0.111.0 uvicorn==0.30.1
