FROM python:3.10-slim

WORKDIR /usr/mlflow

COPY docker/requirements-api.txt .

RUN pip install --no-cache-dir -r requirements-api.txt

COPY src/api /usr/mlflow/src/api

CMD ["uvicorn", "src.api.main:app", "--host", "0.0.0.0", "--port", "8000"]