FROM python:3.10-slim

WORKDIR /usr/mlflow

COPY docker/requirements-ui.txt .

RUN pip install --no-cache-dir -r requirements-ui.txt

COPY src/ui /usr/mlflow/src/ui

CMD ["streamlit", "run", "src/ui/main.py", "--server.address=0.0.0.0", "--server.port=8501"]
