FROM python:3.10-slim

WORKDIR /usr/mlflow

COPY docker/requirements-dev.txt .

RUN pip install --no-cache-dir -r requirements-dev.txt

EXPOSE 8888

CMD ["jupyter", "lab", "--ip=0.0.0.0", "--port=8888", "--no-browser", "--allow-root"]
