FROM python:3.10-slim

WORKDIR /usr/mlflow

COPY docker/requirements-dev.txt .

# 安裝 curl（以及清理暫存，避免 image 過大）
RUN apt-get update \
    && apt-get install -y --no-install-recommends curl \
    && rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir -r requirements-dev.txt

EXPOSE 8888

CMD ["jupyter", "lab", "--ip=0.0.0.0", "--port=8888", "--no-browser", "--allow-root"]
